### ISSUE TITLE
userid not compatible with Stackage LTS

### ISSUE THREAD

**Issue by cdupont** [Happstack/userid#1]
I'm trying to build Happstack-Authenticate 2.3.*.
It requires userid, but this one needs aeson >=0.9 && <0.11
This makes it imposible to compile with Stackage LTS 3.18, which contains aeson-0.8.0.2.

Could you relax the lower bound for userid?

**Comment by stepcut** [comment]
I lowered the bounds. I also attempted to add userid to stackage itself.

userid-0.1.2.3 is now on hackage.
